# Generated by Django 4.2.5 on 2023-09-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('INVALID', 'Invalid')], default='OK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.seed')),
            ],
        ),
    ]
