# Generated by Django 4.2.5 on 2023-09-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_created_at_seed_deleted_at_seed_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='seed',
        ),
        migrations.AddField(
            model_name='seed',
            name='tags',
            field=models.ManyToManyField(related_name='seeds', to='core.tag'),
        ),
    ]
